name: workflow dispatch test
on:
  workflow_dispatch:
    inputs:
      foobar:
        required: true

jobs:
  echo:
    name: Echo
    runs-on: ubuntu-latest

    steps:
      - name: echo
        shell: bash
        run: |
          echo "ECHO ᴇᴄʜᴏ"
